name: Create release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cycjimmy/semantic-release-action@v2.1.3
        with:
          branch: master
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git@8.0.0
